OAT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('menu/', include('menu.urls'), name='menu_urls'),
    path('review/', include('review.urls'), name='review_urls'),
    path('accounts/', include('allauth.urls')),
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='account_login'),
    path('reply/', include('reply.urls')),
    path('contact/', include('contact.urls')),
]

reply/urls.py
from django.urls import path
from .views import Reply
app_name = 'reply'

urlpatterns = [
    # Other URL patterns
    path('reply/<int:pk>/', Reply, name='reply'),
]

review/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('reviews/', views.review_list, name='reviews'),
    path(
        'item-reviews/<int:menu_id>/',
        views.item_reviews, name='item-reviews'),
    path('leave-review/<int:pk>/', views.leave_review, name='leave-review'),
]

reply/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from review.models import Review


class Reply(models.Model):
    """ Model to reply to review on menu """
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Reply to {self.review} by {self.user.username}"

review/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from math import floor


class Review(models.Model):
    """
    Model to create reviews on particular menu dish
    """
    # Rating choice fields
    RATING_CHOICES = (
        (0, '0 - Very Poor'),
        (1, '1 - Poor'),
        (2, '2 - Fair'),
        (3, '3 - Good'),
        (4, '4 - Very Good'),
        (5, '5 - Excellent'),
    )

    menu_item = models.ForeignKey('menu.MenuItem', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = CloudinaryField('image', default=None, blank=True, null=True)
    visit_date = models.DateField()

    class Meta:
        """ Order by time of creation """
        ordering = ["-created_date"]

    def __str__(self):
        return f"Review for {self.menu_item.name} by {self.user.username}"

    @classmethod
    def average_rating(cls, menu_item):
        """
        Function to caculate the average rating to a specific menu
        """
        reviews = cls.objects.filter(menu_item=menu_item)
        if reviews.exists():
            total_rating = sum(review.rating for review in reviews)
            return total_rating / reviews.count()
        else:
            return 0

    @classmethod
    def full_stars(cls, menu_item):
        """
        Function to display the number of full stars
        """
        average_rating = cls.average_rating(menu_item)
        return floor(average_rating)

    @classmethod
    def half_stars(cls, menu_item):
        """ Determine if a half star should be displayed
        based on the average rating of a menu item.

        Parameters:
            menu_item (MenuItem): The menu item to check.

        Returns:
            bool: True if a half star should be displayed, False otherwise.
        """
        average_rating = cls.average_rating(menu_item)
        full_stars = cls.full_stars(menu_item)
        decimal_part = average_rating - full_stars
        return decimal_part > 0.4

review/forms.py
from django import forms
from .models import Review
from menu.models import MenuItem


class ReviewForm(forms.ModelForm):
    """
    Form to leave review
    """
    class Meta:
        model = Review
        fields = [
            # 'menu_item',
            'rating',
            'content',
            'image',
            'visit_date',
        ]
        # Define the visit_date format
        widgets = {
            'visit_date': forms.DateInput(attrs={'type': 'date'}),
        }

review/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages
from .models import Review
from menu.models import MenuItem, Category
from .forms import ReviewForm
from django.core.exceptions import PermissionDenied


def review_list(request):
    """
    View to render reviews with their average rating
    """
    menuitems = MenuItem.objects.all()
    avg = {}
    full_stars = {}
    half_stars = {}

    for item in menuitems:
        avg[item.name] = Review.average_rating(item)
        full_stars[item.name] = Review.full_stars(item)
        half_stars[item.name] = Review.half_stars(item)

    reviews = Review.objects.all()

    categories = Category.objects.all()

    context = {
        'reviews': reviews,
        'categories': categories,
        'menuitems': menuitems,
        'avg': avg,
        'full_stars': full_stars,
        'half_stars': half_stars,
    }

    return render(request, 'review/reviews.html', context)


def item_reviews(request, menu_id):
    """
    View to render detailed reviews and ratings
    from each user to a particular dish
    """

    item = MenuItem.objects.get(id=menu_id)

    print(item.name)
    item_reviews = item.review_set.all()

    context = {
        'item_reviews': item_reviews,

    }

    return render(request, 'review/review_details.html', context)


def leave_review(request, pk):
    """
    View to render a review form for logined user to leave review
    on a particular dish
    """
    menu = MenuItem.objects.get(id=pk)
    form = ReviewForm()
    # nun-login access lead to 403 page
    if not request.user.is_authenticated:
        raise PermissionDenied()

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.menu_item = menu
            review.save()
            messages.success(
                request, 'Your review was successfully submitted!')

        return redirect('item-reviews', menu_id=review.menu_item.id)

    context = {
        'form': form,
        'menu_id': menu.id,
        'menu': menu,
        'form_submitted': False,
    }

    return render(request, 'review/leave_review.html', context)
    

review/templates/review/leave_review.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Render the review form -->
<div class="menu-text">
    <h1 class="text-success">Leave A Review for {{menu.name}}</h1>
</div>
<br>
<br>
<div class="row justify-content-center">
    <div class="col-md-8 mb-2 menu-form mx-auto">
        <form method="POST" action="{% url 'leave-review' menu_id %}" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}         
            <br>
            <div>
                <p>
                    <button class = "btn btn-login" type="submit">
                        Submit
                    </button>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

review/templates/review/review_details.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-success">
    <h1>{{ item_reviews.0.menu_item.name }} Reviews</h1>
    <img src="{{ item_reviews.0.menu_item.menu_image.url }}" alt="Look of {{ item_reviews.0.menu_item.name }}" class="mb-4"
        width="200" height="200">

    {% for review in item_reviews %}
    <div class="card mb-4 text-body">
        <div class="card-body">
            <div class="media">
                <div class="media-body">                    
                    <div class="rating text-warning">
                        {% for i in ""|rjust:review.rating %}
                            <i class="fa fa-star"></i>
                        {% endfor %}
                    </div>
                    <p class="card-subtitle mb-2 text-muted"><strong>{{ review.user.username }}</strong> created on: {{ review.created_date }}
                    </p>
                    <p class="card-text text-Excepturi">{{ review.content }}</p>
                    {% if review.image %}
                    <img src="{{ review.image.url }}" alt="Review Image" class="img-fluid mb-2 menu-image">
                    {% endif %}
                    <p class="card-text"><small class="text-muted">Visited on: {{ review.visit_date }}</small></p>
                    {% if review.reply_set.exists %}
                    <div class="admin-reply border p-3 border-secondary border-2 rounded-3">
                        <p class="card-text"><small class="text-muted"><strong>Manager Replies:</strong></small></p>
                        {% for reply in review.reply_set.all %}
                        <p class="card-text"><small class="text-primary">{{ reply.content }}</small></p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <br>
                    {% if user.is_staff %}                    
                        <a class="btn btn-login" href="{% url 'reply:reply' review.id %}">Reply</a>                    
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- Go back to top icon -->
<a href="#" class="back-to-top" aria-label="back to top">
    <i class="fa fa-arrow-up"></i>
</a>
{% endblock content %}

review/templates/review/reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="menu-text">
    <h1 class ="text-success display-4 fw-bold">Reviews</h1>
    </div>
    <br>
    <br>

    {% for category in categories %}
    <h2 class="border border-dark p-3 mt-4 display-4 fw-bold text-muted">{{ category.name }}</h2>

    <div class="row">
        {% for menuitem in menuitems %}
        {% if menuitem.category == category %}        
        <div class="col-md-3 mb-4">
            <div class="card">
                <img class="menu-image card-img-top" src="{{ menuitem.menu_image.url }}" alt="{{ menuitem.name }}">
                <div class="card-body">
                    <h3 class="card-title menu-name">{{ menuitem.name }}</h3>
                    <div class="rating">                        
                        {% for menu_name, full_stars in full_stars.items %}
                            {% if menu_name == menuitem.name %}
                                {% if full_stars %}
                                    {% for i in ""|rjust:full_stars %}
                                        <i class="fa fa-star text-warning"></i>
                                    {% endfor %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% for menu_name, half_stars in half_stars.items %}
                            {% if menu_name == menuitem.name %}
                              {% if half_stars %}
                                <i class="fa fa-star-half text-warning"></i>
                              {% endif %}                            
                            {% endif %}
                        {% endfor %}
                        {% for menu_name, average_rating in avg.items %}
                          {% if menu_name == menuitem.name %}
                            {% if average_rating %}
                              {{ average_rating|floatformat:1 }}<span> </span><span class="text-muted">out of 5 rating</span>
                            {% endif %}
                          {% endif %}
                        {% endfor %}                        
                    </div>
                    {% if menuitem.review_set.count != 0 %}
                        <p class="card-text">Reviews: <a href="{% url 'item-reviews' menuitem.id %}">{{ menuitem.review_set.count }}</a></p>
                    {% else %}
                        <p class="card-text">Reviews: none</p>
                    {% endif %}
                </div>
            </div>
        </div>        
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>
<!-- Go back to top icon -->
<a href="#" class="back-to-top" aria-label="back to top">
    <i class="fa fa-arrow-up"></i>
</a>
{% endblock %}

review/templates/review/test.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>test{{menu.id}}</p>
<p>{{menu.name}}</p>
{% endblock %}